name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Ensure rsync is available
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Rsync code to server
        run: |
          rsync -az --delete \
            --rsync-path="sudo rsync" \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            --exclude "vendor" \
            --exclude ".env" \
            --exclude "storage/*.key" \
            --exclude "storage/framework/cache/data/*" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_PATH }}

      - name: Run remote post-deploy commands
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
            set -e
            cd "${REMOTE_PATH:-/var/www/shoewalt}"

            # Ensure runtime dirs exist
            mkdir -p storage/framework/{cache,sessions,views} bootstrap/cache

            # Keep runtime writable for web server
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo find storage -type d -exec chmod 775 {} \;
            sudo find storage -type f -exec chmod 664 {} \;
            sudo chmod -R 775 bootstrap/cache

            # Symlink public/storage -> storage/app/public
            php artisan storage:link || true

            # Laravel caches
            php artisan optimize:clear || true
            php artisan migrate --force || true
            php artisan config:cache || true
            php artisan route:cache || true
            php artisan view:cache || true
          EOF
